import type { SectorBlueprint } from './types';

export const SECTOR_BLUEPRINTS: SectorBlueprint[] = [
  { id: 'west-capital', label: 'West Capital', x: 150, y: 450, owner: 'player', capital: 'player', startingBuilding: 'capital' },
  { id: 'west-north', label: 'Northwest Works', x: 325, y: 225, owner: 'player', startingBuilding: 'farm' },
  { id: 'west-south', label: 'Southwest Works', x: 325, y: 675, owner: 'player', startingBuilding: 'factory' },
  { id: 'river-north', label: 'North Crossing', x: 525, y: 145, owner: 'neutral' },
  { id: 'river-center', label: 'Old Mill', x: 530, y: 400, owner: 'neutral' },
  { id: 'river-south', label: 'South Crossing', x: 525, y: 750, owner: 'neutral' },
  { id: 'center-north', label: 'Highland', x: 800, y: 215, owner: 'neutral' },
  { id: 'center', label: 'Central Junction', x: 800, y: 450, owner: 'neutral' },
  { id: 'center-south', label: 'Lowland', x: 800, y: 685, owner: 'neutral' },
  { id: 'east-north-crossing', label: 'East Crossing', x: 1_075, y: 145, owner: 'neutral' },
  { id: 'east-center-crossing', label: 'Stoneworks', x: 1_070, y: 400, owner: 'neutral' },
  { id: 'east-south-crossing', label: 'Marsh Road', x: 1_075, y: 750, owner: 'neutral' },
  { id: 'east-north', label: 'Northeast Works', x: 1_275, y: 225, owner: 'enemy', startingBuilding: 'farm' },
  { id: 'east-south', label: 'Southeast Works', x: 1_275, y: 675, owner: 'enemy', startingBuilding: 'factory' },
  { id: 'east-capital', label: 'East Capital', x: 1_450, y: 450, owner: 'enemy', capital: 'enemy', startingBuilding: 'capital' },
];

export const ROAD_CONNECTIONS: Array<[string, string]> = [
  ['west-capital', 'west-north'],
  ['west-capital', 'west-south'],
  ['west-capital', 'river-center'],
  ['west-north', 'river-north'],
  ['west-north', 'river-center'],
  ['west-south', 'river-center'],
  ['west-south', 'river-south'],
  ['river-north', 'center-north'],
  ['river-center', 'center-north'],
  ['river-center', 'center'],
  ['river-center', 'center-south'],
  ['river-south', 'center-south'],
  ['center-north', 'east-north-crossing'],
  ['center-north', 'east-center-crossing'],
  ['center', 'east-center-crossing'],
  ['center-south', 'east-center-crossing'],
  ['center-south', 'east-south-crossing'],
  ['east-north-crossing', 'east-north'],
  ['east-center-crossing', 'east-north'],
  ['east-center-crossing', 'east-south'],
  ['east-south-crossing', 'east-south'],
  ['east-center-crossing', 'east-capital'],
  ['east-north', 'east-capital'],
  ['east-south', 'east-capital'],
];
